<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->truncate();

        DB::table('users')->insert([
            ['id' => 1, 'f_name' => 'Spencer', 'l_name' => 'Hasting', 'phone' => 8801673138206, 'email' => 'sabrina77proma@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$AAhPrcfA7YOE0Iu46eJEQ.2ejRSwHnr5rrZuLd2J4ojhUZXXmnCWO', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => null, 'cm_firebase_token' => 'cFeNnUqORESpXs0woNJ1is:APA91bFaRfCZVNweXgdx2qiNRlwkH_BpTzb9sBjU31r6IR1ZzaEY_NCAIZqWugHyRSLccvJxjbkRHkZWjGqIfLTVI7spUy8dWWhRPQEAalM_6hsuHIBLuLuXhtFtfHcKDtDBAH8tu7qN', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 3, 'f_name' => 'Sultan', 'l_name' => 'Mahamud', 'phone' => 8801723019980, 'email' => 'sunnysultan1641@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$QutYq7tpbOdazxNqretlTOEl3ILYgGf27wJLQal.1d6zOa9VDrrCW', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[5,8,11,13,14,15]', 'cm_firebase_token' => 'f1INEbw7SseeL17yCulyPg:APA91bEvkhgEOPMxcG3DnW_iCdvwr8oWO8WCATyFMbPtiQq0sfEPyKYP81DPZoYoKfd8w-bJvjHgNfrj1ogdHHFbat_f8B9BBnH3Fdfh2ZQqb6powifVKKNB9q3awaODtpafhPcpms8p', 'status' => 1, 'order_count' => 3, 'login_medium' => null, 'social_id' => null],
            ['id' => 4, 'f_name' => 'Nipon', 'l_name' => 'Roy', 'phone' => 8801747413273, 'email' => 'nipon34.bd@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$VlFUd5tAYILDY/1j43TXF.ddmLeTS43MG9toRnnsskAD9BX364Vj.', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[6,8,9,13,14,16]', 'cm_firebase_token' => 'dlrSenXOQDOL-5yJWNyMOn:APA91bGIBTZbtBIdQCnxLpzmVjVqvQ9S7M30MvWSC8gZOMiOCftaibJFmtIDXbPa7y8cN1iwJ0MsjUFq0oZNCIOe9naHz2eK9hEWu8TJXLBjUILv2Ep4WpOynpYaeIUDfUwSs95phT3g', 'status' => 1, 'order_count' => 1, 'login_medium' => null, 'social_id' => null],
            ['id' => 5, 'f_name' => 'Ashek', 'l_name' => 'Elahe', 'phone' => 8801879762951, 'email' => 'ashek@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$YkYvhY.iEK6JOpXObVnpMO3tyrh3xuPrWqC5l8r8y9ejvd.F3fX5C', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[9,11,16]', 'cm_firebase_token' => 'e6zAZpABQrG3ldEkQt_53I:APA91bHTNEafclAigpVKEvvE1qTycAwkcg0XZXeYQFvrgRivtOCt76dl8hbkLVvwbyI8xtMIadtukQQnG4CO-9bhRHzqoIOuKmdvUu9OPgk9-K14XJ_f_J1u2jCThsvbYxu0-kdv3fJ1', 'status' => 1, 'order_count' => 2, 'login_medium' => null, 'social_id' => null],
            ['id' => 6, 'f_name' => 'Spencer', 'l_name' => 'Hastings', 'phone' => 8801673138207, 'email' => 'sabrina707proma@gmail.com', 'image' => '2021-08-21-61212cd9784be.png', 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$uyEHbNyCkm7vlPd1clZBIu4Z4Jo//sNQuGWX6xN9ARFUT/BRl44Oi', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[5,6]', 'cm_firebase_token' => 'eJZ3MrK8S22SFtBBgbY_1a:APA91bE6lbtoI8N3J-4-eUrir9oRospjkiRIP9otbBXiP8hcP5EtUPukHZSU5zNVeGQ7bEhWD7H24IfyjK-2JvxB97TRmCoj38pEY_XvnuHLP_cM5Nrlvug3upcq7K3xjUDZFd1WeZRQ', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 7, 'f_name' => 'Md', 'l_name' => 'Aziz', 'phone' => 8801975758279, 'email' => 'azizsarkerarc@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$MM.XGZGd2b4ac4wsLJOoY.mNbBm1804Zc.UhM8G55/DbeBgs7ne76', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[5,9,17]', 'cm_firebase_token' => 'dDGShG96Tm68jd2AR8Nyee:APA91bEKl648jKnwgTdtCkyg_Up6r9o3FkD7yumTnAcp-Ov7HUOyMlflxewNQ8PJ86BkwzdYDWXpy4lSApqvwU_eWQvFTlnHDbmOwv9KfaBUBJDBkRB6zj_VCznStX3qfhTzihRLJpBa', 'status' => 1, 'order_count' => 1, 'login_medium' => null, 'social_id' => null],
            ['id' => 8, 'f_name' => 'Alif Emran', 'l_name' => 'Emon', 'phone' => 8801733077939, 'email' => 'alifemu00@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$RdPathYTyHutXJ2aGDADf.xlrgsueL5WlHQ2VLoy99h2x.4z4FRpO', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]', 'cm_firebase_token' => 'dqLeWeUDSvOJ2cpTEDPtFY:APA91bHvpNiaFgApCY6tBKomGb4fn_ltAqd17yfu8DHlCdlhSaRoPMTZ1uWhfdOZ3eVZLfGUsmqaoi4C4dw_LgRUUhmjxScniRSwBAfrQiduH48dh-PHx6WntW0Kz9YQ-BANgZ2xOYa4', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 9, 'f_name' => 'Sultan 0', 'l_name' => 'Mahamud 1', 'phone' => 8801723019985, 'email' => 'sunnysultan1640@gmail.com', 'image' => '2021-08-21-612128ed28af0.png', 'is_phone_verified' => 1, 'email_verified_at' => null, 'password' => '$2y$10$P0Tw9I7.jdCYqnCdJGTKx.ZytpO.AMyEBSaLaBX5PRDDCNTO89AbW', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => null, 'cm_firebase_token' => '8C2DE7700C2C7B23F6B64CA11310BD9BF6C9FE58CBFDC87243D3E0118059CB8A', 'status' => 1, 'order_count' => 5, 'login_medium' => null, 'social_id' => null],
            ['id' => 10, 'f_name' => 'Md Al Imrun', 'l_name' => 'Khandakar', 'phone' => 8801759412381, 'email' => 'md.alimrun@gmail.com', 'image' => '2021-08-21-612129ad7354a.png', 'is_phone_verified' => 1, 'email_verified_at' => null, 'password' => '$2y$10$xfxB5uJe3ikVswyL9zsJqO02FyqEBimCD8T4FEwMxQy9jwome0pli', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => null, 'cm_firebase_token' => 'fpr8zCGnSryywIJVlNyukD:APA91bE40t3Oa7MXgcwCq0vwrdCkdMnyRFXSwiYL77D2OGDT-oGzXLQuuJL1OfvQK9LMWI3EHql0FgHYFTb6uBtft_tFn3ALB2Wj1aqxWf_fskJ3yX568q75MDUP_oPtVzKyoKzF7cfR', 'status' => 1, 'order_count' => 1, 'login_medium' => null, 'social_id' => null],
            ['id' => 11, 'f_name' => 'Kamrujjaman', 'l_name' => 'Joy', 'phone' => 8801733415955, 'email' => 'joy25896@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$4EG8yCPrrx9lU1hnKaCf5O8peh8QIriSbUE94QhAqxUKOgIHnSUUG', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]', 'cm_firebase_token' => 'edDkVtvKQTmXtRfpVw3NmJ:APA91bGnLp2WtzzVbBNT_Zr02earftndIt5OU145ndSewenmKWRpGC_0BTlSUBg3J4dcp9TGdAf0mlS4TT3SHVrJOeXp1sfHCzvr1hgTOEL3FZ6HFRnFOiqfTrCcLU67XWZ4H7LKiAMB', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 12, 'f_name' => 'Spencer', 'l_name' => 'Hastings', 'phone' => 8801673138205, 'email' => 'sabrina777proma@gmail.com', 'image' => '2021-08-22-61214ccf01013.png', 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$ki8MxgaE3a9H7mVE3lPG1OJj/fFuhQ1YOdI49llyPfwkqKiMFSIeG', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[5]', 'cm_firebase_token' => 'd0bm85YVSUu90drRDLC8xi:APA91bEp0lQjMJfnQ25Ww3FJD8nbs8XQE2ywqt4e0OO5z3nQq_1rmsPay7wp5FKxT7Q0svCnMozqxv3LypzXKM_Bf7K7Mc2W6goa6_a3R2QH7dBLABsnGx-GGfcgM82pSuP6ByC4HV2q', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 13, 'f_name' => 'sultan', 'l_name' => 'mahamud 2', 'phone' => 8801723019986, 'email' => 'sultan@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$Ckq2owsQewVUh40z4xk.p.8e3f/AwWpj8C9zjpxko7By579QvKUti', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[5,9,12,13,16]', 'cm_firebase_token' => '8C2DE7700C2C7B23F6B64CA11310BD9BF6C9FE58CBFDC87243D3E0118059CB8A', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 14, 'f_name' => 'demo', 'l_name' => 'demo', 'phone' => 21620123123, 'email' => 'demo@inboxgun.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$urDjzUu8SAXyusgPLGMV/esDpEfkJoe70r6VaB.tmP6D1RYrEqTWy', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[10,12,14,16,17,18,20]', 'cm_firebase_token' => 'cC9WXg3dQIS88hIertKT86:APA91bG_7GgQnN4a0MFMTXiPpm2BDAE691hMUibdFO-vqM0OkVcTeS305RrqidEuzXc4ZW804JWUG8HYkZagM0BgweV76f8zW5YDayG-Qssv25OLT2FoJ5_bl85FsJKHA5YeBnTAdrfG', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 15, 'f_name' => 'hello', 'l_name' => 'yes', 'phone' => 21620555555, 'email' => 'hello@kdmd.ddj', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$iAA63Wx/mnLBsi9z3JQcTOn1pPgerUdSxi0eMjTzN583eWUC.Og5y', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[5,6,7,9,11,12,13,16,17]', 'cm_firebase_token' => 'eRBYIEDfTKe0XCcIiuUyb5:APA91bEJsDnkwsQqPeN12ql8sHrwcFGvg3cpR1DzFiYRO-rAuisuLxSzmH5uYYdiwU2T58byxNn_J_PeADJG6dPl52jq3KW_vgt9Ut97cvOtSTmMZ9O4p9SayGJVkLXazrVR3EgK59Bn', 'status' => 1, 'order_count' => 3, 'login_medium' => null, 'social_id' => null],
            ['id' => 16, 'f_name' => 'Pili', 'l_name' => 123, 'phone' => 8801624343926, 'email' => 'pili@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$aFiRU6GfhisyYvuivj3E3.IoaJYVDIZcmAxRQdNwiDPh2p6YLD2EG', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => null, 'cm_firebase_token' => 'c5eY9Vd6REajo4nmOHv-9U:APA91bF64P1xIPr4nJ5i5yFzRLg8-Bghg2m263tRZ6lKjfaeA0r5toKabxGML71sRLu2nyc96Q-piFI8D2K18bAwdav7MlWfNxkjL_HQJzJ9zTyl8IH_noAtpO0rjw4JZ2JowKsQK3A8', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 17, 'f_name' => 'Pili', 'l_name' => 123, 'phone' => 8801624343928, 'email' => 'marjahan@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$CxHYNyh0l.04J1X6IsQaZe046dJnOJN3EpGBfL.hCDnGTkGUT.sh2', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]', 'cm_firebase_token' => 'dBABDeCFRZGO26YWltLn8k:APA91bEtEJuzpAM4OMDhO8aUIdCHxzEhJVRm0zILTsyD6PU15SKZTzuoc5-DS2jhHGlfoxVlwCbXQbbL_KUSwNVaBQluhkjBFjXONMyz6gyX13560pPeBWopO2CByYiXs-wQ5DXf6Zg3', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 18, 'f_name' => 'Kadir', 'l_name' => 'Atıcı', 'phone' => 905555555555, 'email' => 'kadir@cra-gmbh.de', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$6X7XulFbiIiX9eV5ZQWuGe.iqcP3kwmrAXBdDwcOKXfTkgqUWj46a', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[5,6]', 'cm_firebase_token' => 'cT8SfWUaTNeihfk5xYwyYR:APA91bFuI39NgFe1Ur4fh6jX5y4c1ZOGJxNmJOSAeITT3cBEP4CmM5w9tn7I-PhgIGAgArzKsHaNq-Q0OUe4RJDgLyK-BzzmbXdjLqwohUG6J3x8405SBp6ezoTfu8ur03hj5glnJB_1', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 19, 'f_name' => 'Ali', 'l_name' => 'Mohamed', 'phone' => 201015523902, 'email' => 'foodzy24.com@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$g3A9uFJOfyty2qLZJ2S9KuednoXozzCVkClVsXO7IVMdwUkBe2pIu', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[5,7,9]', 'cm_firebase_token' => 'dikno29WR0emqmWk7SiWSy:APA91bG2E_6LCdHULXiVUbTb2admG1a6UKHB5FKoCSdVA5ywv3hQsx1mX-_81gXsUS7_TO46cvUjhZSPapPAel1z-ZjawJKfWVP7c-VCa9AsDc58eZwm-4Jxs-PuulfHfnuGfrLScNoL', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 20, 'f_name' => 'Dejan', 'l_name' => 'Đusić', 'phone' => 38163627543, 'email' => 'fudonjakg@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$qKAOhopKAUAF7RDuJuLDwOQ3n9W4sPeZ/2oHGeQZoPeuf2ciZSg4W', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => null, 'cm_firebase_token' => null, 'status' => 1, 'order_count' => 1, 'login_medium' => null, 'social_id' => null],
            ['id' => 21, 'f_name' => 'Qwa', 'l_name' => 'Qwa', 'phone' => 919555856525, 'email' => 'asifhkl@fhj.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$cnWcJ1/G9nHmzz4DBnU75uSPyS9TWPoRn2HbSCobLSC4rzfXVUCTe', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[5,6]', 'cm_firebase_token' => 'dZaTkvxgTXSWnZUAwMHahs:APA91bHSE_QrGg_lezHL-gu82AI2DwxDBvPD6jdFHMNp6HCDBy1bAq0nNrKBz-iwKU35yYhTBhUGDTmR8Iq24i7H4BefDHcv4TiCDGwmrk-_joV_sC1QQdvv7DHTBdL5nxaNETBSLfC8', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 22, 'f_name' => 'Zubair', 'l_name' => 'Jamil', 'phone' => 923422643265, 'email' => 'zj.zubair@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$Xc2J2ZC.EA/s5UUeIC2zku0fuR.gxnHFr.yHa8yEN2m7MaRrBXnIW', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]', 'cm_firebase_token' => 'djRjbLwKTfqAIyz-5jIecJ:APA91bGSqbFvjYkrP66ETh9ob6pMuWJX214gRIYss6uWfn0BDrT5Y7WmNOP3ExZ6qNv3TXBTqrk1I5UtzLsEHvMc1oT7QmwENbMCmIkPwols9zDisN4tnr6OfAJUJA1eaw0hkRPk7084', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 23, 'f_name' => 'Aakash', 'l_name' => 'Hameed', 'phone' => 923076153709, 'email' => 'aakashhameed2@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$uwvKHKNgjM9XXDaRYsGnL.HIEHeTKD36eQ72wcvhJfStfruwx.TN6', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]', 'cm_firebase_token' => 'dApCUOnQSkO7sYyXx4bPzg:APA91bEXorfEQttWAoMVxwD-E4gLGeQRHcp7W0b1D16QPZyaibekFtnJTQVjyuzGEO1Ur5DzLa5wAmemf6VWy0OGXBr0zkIESEmEV7o7lrdj5kV1_BGpt6SPFkugdHBBGkmU-edJcRYl', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 24, 'f_name' => 'Sneha', 'l_name' => 'Gupta', 'phone' => 919090809090, 'email' => 'sneha@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$vIXLvd7qIdOnulkY1xyL0.BdYrbcr8jjk5LMcgzOu0ugEjoR1YwNq', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[5,8,10,11,13,14,17,18]', 'cm_firebase_token' => 'edmgveokRJCCaUX-xXsW0X:APA91bH7HeakZklepMKTFxTkUffGPK89EbUjW74WVqgTkN_0O4Dm7XDI93S1tiWmBH8bI__PV_A4XBrakWIjaObA2kRIRK56ubVxDsodV-6AylRQS5StR-gQ78345dSPFbbAwrvgmpJc', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 25, 'f_name' => 'king', 'l_name' => 'ratana', 'phone' => 85592444160, 'email' => 'king@gmail.con', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$CFK3DA1shEr9sVK0wTEIselr/sE8oblIP/NxtXyBntvTdLIEqyZ2W', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]', 'cm_firebase_token' => 'f73ekeuMToKytLFRqKOPeg:APA91bFdQTlFPshn_7n7GKAR4-ueKkps2ki0RuDo0A94QhypIEZtjUwXmbhbZC3An9zQaUIrg09UKtIZKkWG-tNdncrwz5LXU_UZpV8oP1DPr-uVzls9YQhQ6VWRj177QyY0jtRQcycC', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 26, 'f_name' => 'Chinna', 'l_name' => 'Chinna', 'phone' => 918143143790, 'email' => 'chinna.satya390@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$2qZ5tQrC/v3Odv9RgUfdJuz8RVAqxe5.nSXd9VRp2pShZpQYbQsjm', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]', 'cm_firebase_token' => 'fe4lWp9fQmy0q-9cKkDN8x:APA91bEwfungQf8FyrEgtjs-cFgKk4h4s3yrlsDJk3opejdIfNC9J6qii9ss7kE04icTG703CBsFalJjEbNn1YvLMK7DtgDSkCZ02PG0F4jDHbHGVv7eCwWqbCX7fvgQfEn_b0qUMD9C', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 27, 'f_name' => 'V', 'l_name' => 'V', 'phone' => 911234567890, 'email' => 'v@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$EIe7llNNk0P9Pc/z6.7r7e.xB5uuRbSwBZ3LS6HQ0v4wEGBhgBM7C', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[6,8,10,12,14,16,18,20]', 'cm_firebase_token' => 'eAzPyf-JRb-Tso_eH_r4m1:APA91bFarSxrQlMQoe23nG7wzznGFxRY4xOl4rLtD_DmBezspyjUfvODX73zmM5wP3hWMP6bQ-W_bRPfIeey3CMWeemXAmCEr_Am9ki8l7M1ioIr1ntzehfyCA5hviMpxhDC1arXeN7X', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 28, 'f_name' => 'Sreekumar Pankjakshan Nair', 'l_name' => 'Sreekumar Pankjakshan Nair', 'phone' => 919746658386, 'email' => 'gdgdgdgdgd@gddhh.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$ViuRXwmkgfJ44IPoNa4XCOYv9hql5lUCKaL2PnAK/AhYAUi8n3syG', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[5,6,7,9,10,11,12,13,15,16,17,18,20]', 'cm_firebase_token' => '@', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 29, 'f_name' => 'Vijay', 'l_name' => 'Vijay', 'phone' => 917002346789, 'email' => 'vijay@gmail.com', 'image' => '2022-01-11-61dd2204b2d83.png', 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$gt9.5AntzVrGcM.LBNTEueFZ5xzcWOOx5nCBVioH8AL5g2ejJuZMu', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[7,8,10,11,12,13,15,16,17,18,20]', 'cm_firebase_token' => 'eAzPyf-JRb-Tso_eH_r4m1:APA91bFarSxrQlMQoe23nG7wzznGFxRY4xOl4rLtD_DmBezspyjUfvODX73zmM5wP3hWMP6bQ-W_bRPfIeey3CMWeemXAmCEr_Am9ki8l7M1ioIr1ntzehfyCA5hviMpxhDC1arXeN7X', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 30, 'f_name' => 'Anita', 'l_name' => 'Susan', 'phone' => 919582580255, 'email' => 'sdfg@fggh.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$mWEn0Y8..PfaP2fGF9kqMuoUYKr3PuqUWRPLdHAJsSveEvaZWbEme', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => null, 'cm_firebase_token' => 'cDfSwyJwRfqqdoCHVmoJDB:APA91bHopcCCqlEShHm125JUwxsc2n5FnvgPlXNnZosKeAukr0OXY3xOcplHOtczcCPWAexI-zVhYyUj8mjZdVTOaaSv7mbVjnsNzbTQpp1cP8_5jhS6tzEm0m9AH5h9yIyXgrZkSol7', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 31, 'f_name' => 'Anita', 'l_name' => 'Susan', 'phone' => 911234567891, 'email' => 'v@gsg.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$XAcAjpcGZtA5vz5UG.xtdO0MPIyE2PmBO3EXFIEFL22HfXZnk9x9i', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => null, 'cm_firebase_token' => 'cDfSwyJwRfqqdoCHVmoJDB:APA91bHopcCCqlEShHm125JUwxsc2n5FnvgPlXNnZosKeAukr0OXY3xOcplHOtczcCPWAexI-zVhYyUj8mjZdVTOaaSv7mbVjnsNzbTQpp1cP8_5jhS6tzEm0m9AH5h9yIyXgrZkSol7', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 32, 'f_name' => 'V', 'l_name' => 'H', 'phone' => 916437025100, 'email' => 'vh@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$g8KYv30Q8SqsVNapFb/c6uZL8.bM..Q/aYn0R9GoflZNKmRqEYpIi', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[12,13,16,17,18,20]', 'cm_firebase_token' => 'eAzPyf-JRb-Tso_eH_r4m1:APA91bFarSxrQlMQoe23nG7wzznGFxRY4xOl4rLtD_DmBezspyjUfvODX73zmM5wP3hWMP6bQ-W_bRPfIeey3CMWeemXAmCEr_Am9ki8l7M1ioIr1ntzehfyCA5hviMpxhDC1arXeN7X', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 33, 'f_name' => 'Elizabeth', 'l_name' => 'John', 'phone' => 919496462273, 'email' => 'namitha.elizabeth@seeroo.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$PNkylQiV8AlrL0NM73u/xe9BBsdX6zT/S.rpaFQx8xHg4s0TbFpQK', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[16]', 'cm_firebase_token' => 'eFPxmiGfRXKAvvKJfji1Kp:APA91bHhTuLlcoy3ggTFy8r_QMf7lQt47xIBdGAyfL3OMu2DhpTGik0ycJ53iEVkdsjI_fF90jAuaSiQx8jTlB0Nj4gGE42Lq0pTZ7AffiOEQKYHu72_wJD4ZOj6b69CVb7ewH1zBn_I', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 34, 'f_name' => 'Pakalavan', 'l_name' => 'B', 'phone' => 919884159192, 'email' => 'pakalavan16@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$1YlhBAlZv6W.Vb/uOzA3K.AGgxBtFOXxRghsObF18QVfRNdXiqRXm', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => null, 'cm_firebase_token' => 'cIg-fM00TJ-sB4j75xIFRo:APA91bEQevGktoRRBlwaIAPjFByxX8Ga0y3cMnQ6Xn4ObH_h8t89WxMAmV9NCtHsC6WhMJ3xhu0MFD1DrCakFGLp77_YO-kBOd2guFzx5H7xqO71sea-eW13HlcqDDrD_u6lwanTqy9D', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 35, 'f_name' => 'Shhh', 'l_name' => 'Jjajjjj', 'phone' => 10999999999, 'email' => 'shsjsjsjajwjj@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$WA3Qvq4VsOMKns7C3lyz1OzQpt6k/cvMQpIVXP1Q8fGpBhuLvFcKK', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[5]', 'cm_firebase_token' => null, 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 36, 'f_name' => 'Shhh', 'l_name' => 'Hjjh', 'phone' => 17128999999, 'email' => 'jjajajajj@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$WhdX4SQx6B9doU2l1nOAiurPetDz5a8UXsMh0G78.0LzJrf6pegrC', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[5]', 'cm_firebase_token' => 'fNw60k_pT6yMyO6f1tsbcm:APA91bHIJu2BWziV6-t4P0eyukZaZ34ksVCZAApCVmu-hqeRW2rV2MWW3In1cUa_8EdP9Y8H691t9G_1_-5yUNj9P4_8ZVhbMhoDaoLSNcshw6xGP7TvQ0najD6cHcz2ktaqEVCGB__v', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 37, 'f_name' => 'Asdfghj', 'l_name' => 'Asdfghj', 'phone' => 919876543210, 'email' => 'asdfghj@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$pj6TZLrHmpLeQOn2P89AsugLUpjfzDFtslKaSGPaPhmWKfiCCO3ky', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[37]', 'cm_firebase_token' => 'cZJr9uzjQLWDEUP7jPWHXF:APA91bFwaM8OpXgiB4A3OV3l00T87ewjhHW3CbxGKac41zaNkBdGxfPjX-Kuqq95koppS04aH7wF_rYjJk3ElIzYjoXfNDWtexW4KaNtSyMicuO4VV9kLgHd3cBuRh2BHKNX-As0mxYc', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 38, 'f_name' => 'Fatema', 'l_name' => 'Subarna', 'phone' => 8801885576624, 'email' => 'fatema@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$3BL6aWFMiapLBvFryTLiAO8K2RvnG7AT5JGwjUU.VATLGyeZHbNaq', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,37]', 'cm_firebase_token' => '@', 'status' => 1, 'order_count' => 1, 'login_medium' => null, 'social_id' => null],
            ['id' => 39, 'f_name' => 'Idrees', 'l_name' => 'Awais', 'phone' => 923014124781, 'email' => 'idreesawais39@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$8r9Jn3fin08mt4EyWg8WdeJJzJSGccuueda44WaJTg0OA92DwW7ha', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[9,11,12,14,15,17]', 'cm_firebase_token' => 'fHkRFa3PTg-P3jIFo42obc:APA91bFUbtm4EPUK2flA8uH5Ns-_gxyobLzxwxVEDGJmbgKXATteoL-lXqglPuG9ckFu5O-DbGicXBEDuAE1254_oWz7AcagcIS5jD0YNeCdaPByWJvO0tYIcjISpfRYHjj7Mra93cLp', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 40, 'f_name' => 'hahaS', 'l_name' => 'ASJBHDS', 'phone' => 919029765478, 'email' => 'ASCZC@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$hc6aZIQjNur70/Iw1R7OVuvK2XzUTpYM8aEHnF6QP0mn6U4jrJp4q', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => null, 'cm_firebase_token' => 'ch6QpPKFSeSEuNOVw3tUJB:APA91bHJjS7U8b1JgU1IKXFpXFLay181jJm0Lv5UT-viEtXYKaURGxNMaohAvZW8cInNE_mDzqLgdnDRxaUxnM5bRn0EXRYAyjrJbiL66f3zF3GdyiT5ZmcFgwY_eilao3OtXNUg_cFL', 'status' => 1, 'order_count' => 2, 'login_medium' => null, 'social_id' => null],
            ['id' => 41, 'f_name' => 'Tanvir', 'l_name' => 'Mahmud', 'phone' => 8801775893233, 'email' => 'tmtomalkh@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$KuNg3.gPk2BRz8G98NMepueXugmun6qpnhChI209QuskS18UuDEwi', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => null, 'cm_firebase_token' => null, 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 42, 'f_name' => 'M', 'l_name' => 'M', 'phone' => 917822954918, 'email' => 'manojgrey112@gmail.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$N700cryEuGWTeZrofUg5YeDWqRkXF7h1EYjaNQARIjv1tDAN.yqJG', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[5,6,7,8]', 'cm_firebase_token' => 'eRRChFrPSJy1dQsyxb4f4f:APA91bEoyWFrnyzh1zOzAT9b5Q9u__4B1et2qFqai3cHdUllkqIO23Ylbdfrlfe0H6aHJFEy_rbofdCBprrQqMsFUKABLv_Grfp7-XVlt9NjFZZTfAuWnI38JqCyiymopvk-1Rn5LQ-w', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null],
            ['id' => 43, 'f_name' => 'Leo', 'l_name' => 'Leonardo', 'phone' => 40725042424, 'email' => 'leo@leo.com', 'image' => null, 'is_phone_verified' => 0, 'email_verified_at' => null, 'password' => '$2y$10$5genuI4SbXJZ1tKjOfv9aOPiofV5V61dnzNvPL0Sxz2cwe1cM/LUK', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'interest' => '[5,11,18]', 'cm_firebase_token' => 'eURuwnESR1-qFPfL5rD4s_:APA91bGvlTUPol6UVUjWFyysWSvKBqaSpcZCmO-k0YRUd7KliX0PO4xM7JXmFL4UEVpckUghoNDdzWgyVXJR_mNNIMdiT9sCBrwUkLmAvLCtwq5ZEGFOznmARIm2Nn2HOP2EqSbYcbjE', 'status' => 1, 'order_count' => 0, 'login_medium' => null, 'social_id' => null]
        ]);


    }
}
