<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VendorsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('vendors')->truncate();

        DB::table('vendors')->insert([
            ['id' => 1, 'f_name' => 'Joshef', 'l_name' => 'Doe', 'phone' => 910111111111, 'email' => 'joshef.doe1025822@gmail.com', 'email_verified_at' => null, 'password' => '$2y$10$f5Ujqi05wF33.RTiCwjOOumpFIcrmZakSzXAJnNxLdNW1DE8j7a8G', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'bank_name' => null, 'branch' => null, 'holder_name' => null, 'account_no' => null, 'image' => null, 'status' => 1, 'firebase_token' => null, 'auth_token' => null],
            ['id' => 2, 'f_name' => 'Pichart', 'l_name' => 'Anthony', 'phone' => 8801710000000, 'email' => 'test.restaurant@gmail.com', 'email_verified_at' => null, 'password' => '$2y$10$GkV8QOoxu8hMGlRUiHqpP.DuT2M226k5g/99pT4.STuhGf5pNHPGG', 'remember_token' => 'Tfu3LvZWpS8KzPaMJtwGNPYDxCQ6CLWORziyJWsoIVFCbzcmZiIzhvVG7rrc', 'created_at' => now(), 'updated_at' => now(), 'bank_name' => null, 'branch' => null, 'holder_name' => null, 'account_no' => null, 'image' => '2021-08-22-61214e5a0db7d.png', 'status' => 1, 'firebase_token' => 'ejNXMX_9Ssq7oDxuNeXyn-:APA91bFrnfuAM6Ie41QMnUXQXSvDZGo5QR0Ldfi2hOm-2gi9PZ1KIwvBG6AEaz7u35clTrkZMqNWx08Qk3E-rIL_LwiazQWxK4UDaMAwwJWBC4giM3OIlH9_9FuAO_qHZlEe2gaX9Ymf', 'auth_token' => 'nmsPX9plROacSxujOnSMs34Pjt1xu82qoaai5In6F0PTUN3xJPM9BOAj7PshwjFVtWND4yUb5HpiDj3QbkzRxi8mKfeNfc3Ecx6E4PQ2kse54omFXirOINsl'],
            ['id' => 3, 'f_name' => 'Nipon', 'l_name' => 'Roy', 'phone' => 8801747413273, 'email' => 'nipon34.bd@gmail.com', 'email_verified_at' => null, 'password' => '$2y$10$JwU.Z0eXrpIR6vjkJUKy3.lJ4Wj8a3hctJ0.4m9EcNyGDPjJMk4vC', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'bank_name' => null, 'branch' => null, 'holder_name' => null, 'account_no' => null, 'image' => null, 'status' => 1, 'firebase_token' => null, 'auth_token' => null],
            ['id' => 4, 'f_name' => 'Jakatta', 'l_name' => 'Potin', 'phone' => 88525695888, 'email' => 'test.restaurant1@gmail.com', 'email_verified_at' => null, 'password' => '$2y$10$KhQKyf4AOnEqHE3tWB51x.nOj.orejD2QpBrpnkn9QLOyt3jd.sam', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'bank_name' => null, 'branch' => null, 'holder_name' => null, 'account_no' => null, 'image' => null, 'status' => 1, 'firebase_token' => 'e_w7Vuv9SmyyTfGHYwhMYP:APA91bEOc251yRiaSc116fUQHuVatD01wPqf0AvD4tFlVew2UN7Fq6U83Y999-brut0P5SBrRR3Ott1fwYymzXnp1dChdM5GueJKyiMga6Xp9syZBWmGTjzHBC_l_ks1FoPX6u_CMlfP', 'auth_token' => 'lNsm7hDeqo120RwSGXy6SRxcGxXvpvd2cPRL60BmCdx6vshsbZ9DQ59Z2ykK4iP9x7SfPxblheGVWBlUMY4YeYo2zYpwarDQD3cMdmTCbmHYdzoCb1cPBgV4'],
            ['id' => 5, 'f_name' => 'Rimison', 'l_name' => 'Doe', 'phone' => 6024588888, 'email' => 'test.restaurant2@gmail.com', 'email_verified_at' => null, 'password' => '$2y$10$oGyCkIDOYbC22hTgkkiA6OrLIQ3GGlu40nyQKxmLGvsOysvuKWjsy', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'bank_name' => null, 'branch' => null, 'holder_name' => null, 'account_no' => null, 'image' => null, 'status' => 1, 'firebase_token' => null, 'auth_token' => null],
            ['id' => 6, 'f_name' => 'Yello', 'l_name' => 'Thid', 'phone' => 8565222222, 'email' => 'test.restaurant3@gmail.com', 'email_verified_at' => null, 'password' => '$2y$10$4n1iOICzuctagsDSrofS/usNmeITSmrJ5iEmLpKU7GfoxOkFDjwA6', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'bank_name' => null, 'branch' => null, 'holder_name' => null, 'account_no' => null, 'image' => null, 'status' => 1, 'firebase_token' => null, 'auth_token' => null],
            ['id' => 7, 'f_name' => 'Mirra', 'l_name' => 'Roy', 'phone' => 12562458744, 'email' => 'test.restaurant4@gmail.com', 'email_verified_at' => null, 'password' => '$2y$10$rOzu5Is.Xxs.Xr32RLyHuuqnVZ4scL3xRWP8S.enWB19duo.8Ed9S', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'bank_name' => null, 'branch' => null, 'holder_name' => null, 'account_no' => null, 'image' => null, 'status' => 1, 'firebase_token' => 'e_w7Vuv9SmyyTfGHYwhMYP:APA91bEOc251yRiaSc116fUQHuVatD01wPqf0AvD4tFlVew2UN7Fq6U83Y999-brut0P5SBrRR3Ott1fwYymzXnp1dChdM5GueJKyiMga6Xp9syZBWmGTjzHBC_l_ks1FoPX6u_CMlfP', 'auth_token' => '0LFDyXK2Gio6H0Oo9JEB55PhAv5IOp3THXF3Txzd1dP0OGdG15yJ6Cc0yBPj0t4EmiRi1agOSigdCCsSdE9uScsCGa5avNZd0MoRRd9A6MC21lmBno2O66kY'],
            ['id' => 8, 'f_name' => 'Kutman', 'l_name' => 'Beneti', 'phone' => 12584555555, 'email' => 'test.restaurant5@gmail.com', 'email_verified_at' => null, 'password' => '$2y$10$pCGDs0eVCqjR4mRliFnZSOdIsMigqzOoJbXANQAQUYLk8GuKecG5y', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'bank_name' => null, 'branch' => null, 'holder_name' => null, 'account_no' => null, 'image' => null, 'status' => 1, 'firebase_token' => null, 'auth_token' => null],
            ['id' => 9, 'f_name' => 'Sunny', 'l_name' => 'Sultan', 'phone' => 880100000000, 'email' => 'test.restaurant6@gmail.com', 'email_verified_at' => null, 'password' => '$2y$10$tSDv3gvQEthGwH3ZaM2vau0vhWxV3.pZDtDPq06sKiP26Qi1UsNay', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'bank_name' => null, 'branch' => null, 'holder_name' => null, 'account_no' => null, 'image' => null, 'status' => 1, 'firebase_token' => null, 'auth_token' => null],
            ['id' => 10, 'f_name' => 'Sumitro', 'l_name' => 'Das', 'phone' => 91025888888, 'email' => 'test.restaurant7@gmail.com', 'email_verified_at' => null, 'password' => '$2y$10$bBaATHdS6quLOqItaqSvCek/N/oaMOZd3PW2eaLhI7qb5tLg0Djuq', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'bank_name' => null, 'branch' => null, 'holder_name' => null, 'account_no' => null, 'image' => null, 'status' => 1, 'firebase_token' => null, 'auth_token' => 'ViAVg0CTdVZcm6sLjVhQZrVk1VDI1i4gpXTYuoIo10jM0ddGeDox0xxLC4KnHbe1PFYwhayqpXZdRWJFXbszjkBe9DK3oZJGkNBhwgr3mpOBOWzip2YPiCZ8'],
            ['id' => 11, 'f_name' => 'Pinku', 'l_name' => 'Islam', 'phone' => 91025558884, 'email' => 'test.restaurant8@gmail.com', 'email_verified_at' => null, 'password' => '$2y$10$hTb7ShXmMUXPrqSoD3iPbeWKkZOmrK1uI/jVW3Ta8I8jz9ToBkix.', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'bank_name' => null, 'branch' => null, 'holder_name' => null, 'account_no' => null, 'image' => null, 'status' => 1, 'firebase_token' => 'dwwfnoM1ShqmZ23-yH9QN1:APA91bFRhIavLsVybuZnnTmtUMEOUx_z3QAMY78PR8dRmbVfMAS1jTQPHcEPh6NzoQjtEDntM_kF8GJLhC--afQ_UDtEBwkEUKXtaO5rxrevSJVzjIuFBGLptqyUN8SxUbP6_hP4H_ve', 'auth_token' => 'stdm9vbdhsjdFYB7RqzK3iTkPJyJckROE2cz77dYNeZHd0YmKxAC1fsTc7Tkmtgs1gzvX5s5l8Vb5Yvbx33oKINbCQ5ldDEMIu5Y0c9MtLR7aUigdbOUO3Ht'],
            ['id' => 12, 'f_name' => 'Punchuk', 'l_name' => 'Yangru', 'phone' => 2541255888, 'email' => 'test.restaurant10@gmail.com', 'email_verified_at' => null, 'password' => '$2y$10$5D88uGCkHKd3ipRQ2A5Kgu.yGW.LVVbkDQXp7orL8UhVbPdCFNOiK', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'bank_name' => null, 'branch' => null, 'holder_name' => null, 'account_no' => null, 'image' => null, 'status' => 1, 'firebase_token' => null, 'auth_token' => null],
            ['id' => 13, 'f_name' => 'Jhon', 'l_name' => 'Chung', 'phone' => 212588888, 'email' => 'test.restaurant13@gmail.com', 'email_verified_at' => null, 'password' => '$2y$10$DpOcE/PmXp6m9S5Ps1ssBOifQ0av303cDC9YEteaBjouhZSR0Ha/.', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'bank_name' => null, 'branch' => null, 'holder_name' => null, 'account_no' => null, 'image' => null, 'status' => 1, 'firebase_token' => null, 'auth_token' => null],
            ['id' => 14, 'f_name' => 'Jibona', 'l_name' => 'Posta', 'phone' => 91021100000, 'email' => 'test.restaurant12@gmail.com', 'email_verified_at' => null, 'password' => '$2y$10$kV0C7LSujfDT7VX653qLVuQZwtti.JerqpGtXARW5pod8zEEhYW96', 'remember_token' => null, 'created_at' => now(), 'updated_at' => now(), 'bank_name' => null, 'branch' => null, 'holder_name' => null, 'account_no' => null, 'image' => null, 'status' => 1, 'firebase_token' => 'eqqG_NSBQJGfwwZ8s2Z5gk:APA91bFG8XLdQ0IE69UaFOztNl54OEWiinqI9Zu-AixOY8pW280UaWrhX6CvyC-203YUG4qg24FO6azyO3EzeWCel4SnrceYEXLJF6JjroblcR6lA67dz5lYJKcjf8cu27BC4evKjkFG', 'auth_token' => '4Ja8QuWPYnO2BQmeibVNromnjtmdcocWYrfNA2O1JtuwLKIXP7CWhS8w3J1y2tBG2hZt3xwDx32yTFHIfcKFXQ0DcFeHsozeewmKg2OEwzk73lMogZ1LbVzC']
        ]);


    }
}
